jQuery(function ($) {
    $('body').ypoPlugin({
        fontFamily: [],
        copyRight: 'YPO Copyrights Reserved',
        multiMedia: 'xxxxxxx',
        scroller: true,
        menuWidth: false,
        mobileMenu: true,
        slideMenu: false,
        slideType: 'left',
        siteMap: true,
        countryCode: ['+1'],
        show_countryCode: false,
        phoneNumbers: ["(xxx) xxx-xxxx"],
        phoneInfos: ["Telephone Number of XXXXXX"],
        phoneLinks: ["/general-appointment.html"],
        faxNumbers: ["(xxx) xxx-xxxx"],
        faxInfos: ["Fax Number of XXXXXX"],
        responseHeight: false,
        responseHeight_upto: 480,
        responseList: ["#Banner"],
        swapBanner: false,
        swapBanner_after: 480,
        leftSidebar: false,
        leftSidebar_upto: 700,
        accordion: false,
        tabAccord: false,
        tabAccord_upto: 640,
        stickyHeader: false,
        stickyHieght: 120,
        onView: false,
        onViewList: (''),
        parallaxEffect: false,
        parallaxList: (''),
        ypoForms: false,
        gdpr: false,
        accessibility: false,
        fontResize: false,
        fontResizeList: (''),
        removeElements: ('#Banner-Container,#Banner-Container-S,#Map-Container'),
        removeId: ('#Slider1, #flexisel1'),
        removeClass: ('rslides')
    });
});
